apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.7
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  targetNamespace: ingress-nginx
  install:
    timeout: 10m
  values:
    controller:
      service:
        type: LoadBalancer
      config:
        server-snippet: |
          location / {
            header_filter_by_lua_block {
              if ngx.status == 404 then
                return ngx.redirect("https://google.com", 301)
              end
            }
          }
