apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-metallb.yaml
  - metallb-config.yaml
  - namespace-ingress-nginx.yaml
  - helmrepository-ingress-nginx.yaml
  - helmrepository-bitnami.yaml
  - ingress-nginx.yaml
